# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - windows
  - linux
  - osx
julia:
  - 1.1
  - nightly
matrix:
  fast_finish: true
  include:
    - os: windows
      arch: x86
      julia: 1.1
      name: "Julia 1.1 (32bit)"
    - os: windows
      arch: x86
      julia: nightly
      name: "Julia nightly (32bit)"
  allow_failures:
    - julia: nightly
notifications:
  email: false
before_install: julia -e 'using Pkg; Pkg.add([PackageSpec(url="https://github.com/DrChainsaw/NaiveNASlib.jl"), PackageSpec(url="https://github.com/DrChainsaw/NaiveNASflux.jl")]);'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
